CREATE TABLE IF NOT EXISTS `cse1_new1` (
  `id` varchar(7) DEFAULT NULL,
  `name` varchar(30) DEFAULT NULL,
  `branch` varchar(30) DEFAULT NULL,
  `campus` varchar(3) DEFAULT NULL,
  `breadthSubject pref1` varchar(35) DEFAULT NULL,
  `breadthSubject pref2` varchar(23) DEFAULT NULL,
  `breadthSubject pref3` varchar(23) DEFAULT NULL,
  `breadthSubject pref4` varchar(46) DEFAULT NULL,
  `breadthSubject pref5` varchar(23) DEFAULT NULL,
  `breadthSubject pref6` varchar(27) DEFAULT NULL,
  `breadthSubject pref7` varchar(134) DEFAULT NULL,
  `breadthSubject pref8` varchar(41) DEFAULT NULL,
  `breadthSubject pref9` varchar(118) DEFAULT NULL,
  `breadthSubject pref10` varchar(32) DEFAULT NULL,
  `O` varchar(10) DEFAULT NULL,
  `AOA` varchar(3) DEFAULT NULL,
  `PPL` varchar(3) DEFAULT NULL,
  `COA` varchar(3) DEFAULT NULL,
  `TOC` varchar(3) DEFAULT NULL,
  `COAL` varchar(10) DEFAULT NULL,
  `PPLL` varchar(10) DEFAULT NULL,
	--`id` varchar(7) NOT NULL,
  `RNo` int(2) NOT NULL DEFAULT '0',
  `Name` varchar(50) NOT NULL,
  `Gender` varchar(1) NOT NULL,
  `Branch` varchar(5) NOT NULL,
  `Class` int(1) NOT NULL,
  `Password` varchar(32) NOT NULL,
  `Picture` varchar(30) NOT NULL,
  `PhoneNo` varchar(10) NOT NULL DEFAULT '0',
  `Position` varchar(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


